development:
  host: localhost
  database: jaftodo_development

test:
  host: localhost
  database: jaftodo_test

# set these environment variables on your prod server
production:
  uri: <%= URI.parse(ENV['MONGOHQ_URL']) %>
